# Generated by Django 3.2.12 on 2024-01-14 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=255)),
                ('threshold', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ChemicalTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('test_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('water_temperature', models.FloatField()),
                ('air_temperature', models.FloatField()),
                ('water_filter_flow', models.FloatField()),
                ('pH', models.FloatField()),
                ('water_turbidity', models.FloatField()),
                ('light_intensity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('pH', models.FloatField()),
                ('kH', models.FloatField()),
                ('nitrites', models.FloatField()),
            ],
        ),
    ]
