# Generated by Django 5.0.1 on 2024-01-20 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquariumapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FCMToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
