# Generated by Django 5.0.1 on 2024-01-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquariumapp', '0003_chemicaltest_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemicaltest',
            name='status',
            field=models.CharField(choices=[('En attente', 'En attente'), ('En cours', 'En cours'), ('Terminé', 'Terminé'), ('Échec', 'Échec')], default='En attente', max_length=20),
        ),
    ]
