# Generated by Django 5.0.1 on 2024-01-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquariumapp', '0004_chemicaltest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_temperature', models.FloatField()),
                ('air_temperature', models.FloatField()),
                ('water_filter_flow', models.FloatField()),
                ('pH', models.FloatField()),
                ('water_turbidity', models.FloatField()),
                ('light_intensity', models.FloatField()),
            ],
        ),
    ]
